<?php

namespace AppBundle\Repository;

/**
 * NewsletterEmailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterEmailsRepository extends \Doctrine\ORM\EntityRepository
{
}
